---
title: "Untitled"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
date: "2023-10-18"
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
options(scipen = 999)
library(tidyverse)
library(dplyr)
library(DT)
library(viridis)
library(janitor)
```

```{r}
acfrs_general_purpose_22 <- readRDS("data/data_from_dbsite_2022.RDS") %>% 
  filter(category == "General Purpose") %>% 
  select(-c(5:11, category, has_unconfirmed, component_unit_of_id)) %>% 
  mutate(name = str_to_lower(name)) %>% 
  rename(government_ID = census_id) %>% # census_id in Acfrs database is actually government_ID
# some government_ID in ACFRs has 13 characters-> need to add 0
  mutate(government_ID = ifelse(str_length(government_ID) < 14, paste0("0", government_ID), government_ID)) 
```

```{r}
# States from ACFRS 2022
acfrs_state_2022 <- acfrs_general_purpose_22 %>% filter(str_detect(name, "(state of)|(district of columbia)|(commonwealth)")) %>% 
  filter(!str_detect(name, "yap|kosrae")) %>% 

  #clean state names to match with those names in census population data 
  mutate(name = str_remove(name, "state of "),
        name = str_remove(name, "commonwealth of "),
        name = str_remove(name, "government of the ")) %>% 
  #left_join(states_population) %>% 
  #select(-c(year, has_unconfirmed)) %>% 
  filter(!str_detect(name, "(iowa single audit)|(puerto rico)")) %>% 
  rename(state.abb = state) %>% 
  select(-c(government_ID))

acfrs_state_2022 %>% write.csv("output/state_gov_2022.csv")
```


```{r }
#Joining acfrs states & census states: state_gov_2020
state_gov_2021 <- read.csv("output/state_gov_2021.csv") %>% select(-c(X, government_ID, FIPS, geoID, population))
state_gov_2020 <- read.csv("output/state_gov_2020.csv") %>% select(-c(X, government_ID, FIPS, population))

state_3y <- state_gov_2021 %>% 
  rbind(state_gov_2020) %>% 
 rbind(acfrs_state_2022) 


state_3y %>% select(state.abb, name, year, net_pension_liability) %>% 
  pivot_wider(names_from = year, values_from = net_pension_liability) %>% 
  mutate(year21_to_20 = `2021`/`2020`,
         year22_to_21 = `2022`/`2021`) %>% 
  arrange(desc(year22_to_21)) %>% 
  select(state.abb, year22_to_21) 
```

# State Government: 2020, 2021, 2022

```{r}
datatable(state_3y)
```
# State governments: Net Pension Liabilities
```{r fig.width=15, fig.width=15}

state_3y %>% #filter(state.abb == "CA")
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(name, net_pension_liability), group = year) +
  geom_col(aes(fill = year), position = "dodge") +
  # scale_color_viridis(discrete=TRUE) +
  scale_y_continuous(breaks = c(50000000000, 100000000000, 150000000000),
                   label = c("$50B", "$100B","$150B")) +
  
    scale_fill_manual(values = c("grey","black","orange")) +
  
  labs(title = "Net Pension Liabilities of State Governments in 3 years: 2020, 2021, 2022",
       x = "",
       y = "Net Pension Liabilities", 
       caption = "Four states have not released 2022 ACFRs: AZ, CA, NV, OK\n Four states whose ACFRs are being processed: HI, IL, MT, NM") +

  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) 
  
  
# 4 are behind:       AZ" "CA" "NV" "OK""
# 4 being proccessed:  "HI" "IL" "MT"  "NM"
```
# State governments: Total Liabilities
```{r fig.width=15, fig.width=15}

state_3y %>% #filter(state.abb == "CA")
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(name, total_liabilities), group = year) +
  geom_col(aes(fill = year), position = "dodge") +
  # scale_color_viridis(discrete=TRUE) +
  scale_y_continuous(breaks = c(100000000000, 200000000000,300000000000, 400000000000, 500000000000),
                   label = c("$100B","$200B", "$300B", "$400B", "$500B")) +
  
    scale_fill_manual(values = c('#D9AF6B', '#AF6458', '#68855C')) +
  
  labs(title = "Total Liabilities of State Governments in 3 years: 2020, 2021, 2022",
       x = "",
       y = "Total Liabilities", 
       caption = "Four states have not released 2022 ACFRs: AZ, CA, NV, OK\n Four states whose ACFRs are being processed: HI, IL, MT, NM") +

  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) 
  
  
# 4 are behind:       AZ" "CA" "NV" "OK""
# 4 being proccessed:  "HI" "IL" "MT"  "NM"
```

# State governments: Revenues

```{r fig.width=15, fig.width=15}
state_3y %>% #filter(state.abb == "CA")
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(name, revenues), group = year) +
  geom_col(aes(fill = year), position = "dodge") +
  # scale_color_viridis(discrete=TRUE) +
  scale_y_continuous(breaks = c(100000000000, 200000000000,300000000000, 400000000000, 500000000000),
                   label = c("$100B","$200B", "$300B", "$400B", "$500B")) +
  
    scale_fill_manual(values = c('#526A83', '#625377', '#68855C')) +
  
  labs(title = "Revenues of State Governments in 3 years: 2020, 2021, 2022",
       x = "",
       y = "Revenues", 
       caption = "Four states have not released 2022 ACFRs: AZ, CA, NV, OK\n Four states whose ACFRs are being processed: HI, IL, MT, NM") +

  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) 
```

# County governments: The top 50


```{r fig.width=15, fig.width=15}
 county_acfrsID_20_21 <- readRDS("county_acfrsID_20_21.RDS")
county_acfrsID_20_21 %>% arrange(name) %>% select(state.abb, name, id, population) %>% distinct()

# top50_county_census <- readRDS("top50_county_census.RDS")
# county_2022 <- acfrs_general_purpose_22 %>% 
#   filter(id %in% county_acfrsID_20_21$id) %>% rename(state.abb = state)
# 
# top50_county_22 <- county_2022 %>% 
#   left_join(top50_county_22) %>% 
#   drop_na(population) %>% select(state.abb, name, id, population, year, net_pension_liability)
#   
#   top50_county_20 <- county_acfrsID_20 %>% arrange(desc(population)) %>% 
#     #filter(id %in% top50_county_census$id)
#     
#     slice(1:50) %>% mutate(year = 2020)
#   
#   top50_county_21 <- county_acfrsID_21 %>% arrange(desc(population)) %>% slice(1:50) %>% mutate(year = 2021)
#   
#  county_dp <-  top50_county_20 %>% rbind(top50_county_21) %>% 
#     rbind(top50_county_22)  
    
# saveRDS(county_dp, "county_dp.RDS")
```
 
```{r}
county_dp <- readRDS("county_dp.RDS")
county_dp %>% 
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(name, net_pension_liability), group = year) +
  geom_col(aes(fill = year), position = "dodge") +
  # scale_color_viridis(discrete=TRUE) +
  scale_y_continuous(breaks = c(15000000000, 10000000000,5000000000),
                   label = c("$15B","$10B", "$5B")) +

    scale_fill_manual(values = c('#1A4E6B', '#C068A8', '#F4AB32')) +
  
  labs(title = "Net pension Liabilities\nTop 50 Counties in 3 years: 2020, 2021, 2022",
       x = "",
       y = "net_pension_liability", 
       caption = "") +

  theme_minimal() +
    theme(axis.text.x = element_text(angle = 90)) 

```

